### ISSUE TITLE
Support for Ruby 1.9.2

### ISSUE THREAD

**Issue by chrismatthieu** [tropo/tropo-provisioning#3]
This gem seems to work well under Ruby 1.8.7 but not under Ruby 1.9.2.  Create User is failing but so are other methods...

**Comment by chrismatthieu** [comment]
A couple of issues:
- It looks like the user needs to add a slash to the end of PROV_API_BASE_URI in SMSified when using Ruby 1.9.2 for the login to to work such as: 

ENV['PROV_API_BASE_URI'] = "https://api.smsified.com/v1/"

Note: Other resources fail in SMSified with the slash at the end of the URL
- The Create-User method is failing (as are most of the other REST calls) using Ruby 1.9.2.  The problem seems to be in the request method of tropo_client.rb.  When calling the create_user method Tropo responses as follows:

TropoError: 400: Bad Request - {
  "error": "error parsing JSON request entity - are you sure you set the correct Content-type?: Encountered \"<EOF>\" at line 0, column 0.\u000aWas expecting one of:\u000a    <DIGITS> ...\u000a    \"null\" ...\u000a    \"NaN\" ...\u000a    \"Infinity\" ...\u000a    <BOOLEAN> ...\u000a    <SINGLE_QUOTE_LITERAL> ...\u000a    <DOUBLE_QUOTE_LITERAL> ...\u000a    \")]}\'\n\" ...\u000a    \"{\" ...\u000a    \"[\" ...\u000a    \"-\" ...\u000a    "
}
    from /Users/christoffe/.rvm/gems/ruby-1.9.2-p180/gems/tropo-provisioning-0.0.22/lib/tropo-provisioning/tropo_client.rb:183:in `request'
    from /Users/christoffe/.rvm/gems/ruby-1.9.2-p180/gems/tropo-provisioning-0.0.22/lib/tropo-provisioning/tropo_client.rb:66:in`post'
    from /Users/christoffe/.rvm/gems/ruby-1.9.2-p180/gems/tropo-provisioning-0.0.22/lib/tropo-provisioning/tropo_provisioning.rb:132:in `create_user'
    from (irb):199
    from /Users/christoffe/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in`<main>'

Note: This works in Ruby 1.8.7

**Comment by jsgoecke** [comment]
Should be fixed, give it a try.
