### ISSUE TITLE
creating a user requires first_name, & last_name

### ISSUE THREAD

**Issue by johntdyer** [tropo/tropo-provisioning#5]
Need to fix the docs and the method. Also make sure we fix the validation method to ensure it checks for these params

**Comment by johntdyer** [comment]
https://github.com/tropo/tropo-provisioning/commit/63f9e2489f271b711c0d655e775d1c86f71bd45a

**Comment by JustinDupree** [comment]
I am currently away on vacation until the 27th of September; if you know an alternate member of Voxeo Labs that is capable of handling your need, please relay your message directly.  If you're unsure of the correct party to reach, please relay your message to support@tropo.com and a member of the Customer Experience team will be able to help you out.

Thank you!

Justin Dupree
Director of Customer Experience
Voxeo Labs
